language: php # that way we get composer
php:
  - 5.4
install:
  - git config --global init.templatedir "`pwd`"
  - git config --global user.email "travis@mailinator.com"
  - git config --global user.name "Travis Bot"
  - "mkdir -p ~/src/shunit2"
  - "git clone git://github.com/deniscostadsc/shunit2.git ~/src/shunit2"
  - "sudo apt-get install subversion"
  - "svn checkout https://svn.code.sf.net/p/ctags/code/trunk ctags-trunk"
  - "cd ctags-trunk"
  - wget https://gist.github.com/complex857/5693196/raw/14a770b436b5116eb22ec65492d8c0e8a4271210/0000-PHP-parser-rewrite-full-string-parameters.patch
  - svn patch 0000-PHP-parser-rewrite-full-string-parameters.patch
  - autoconf
  - autoheader
  - ./configure
  - make
  - sudo make install
script:
  - "tests/all.sh"
