language: php # that way we get composer
php:
  - 5.4
install:
  - composer self-update
  - git config --global init.templatedir "`pwd`"
  - git config --global user.email "travis@mailinator.com"
  - git config --global user.name "Travis Bot"
  - "mkdir -p ~/src/shunit2"
  - "git clone git://github.com/deniscostadsc/shunit2.git ~/src/shunit2"
  - curl -sS https://getcomposer.org/installer | php
  - sudo mv composer.phar /usr/local/bin/composer
script:
  - "tests/all.sh"
